version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install -g newman@latest newman-reporter-htmlextra@latest
  build:
    commands:
      - echo "🚀 Running API tests with Newman..."
      - newman run Postman_Collections/colletionjson.json --reporters cli,htmlextra --reporter-htmlextra-export report.html || true
      - echo "✅ Test completed. Uploading report to S3..."
      - aws s3 cp report.html s3://tiki-api-report-bucket/$(date +%F_%H-%M)-report.html
      - |
        if grep -q "failure" report.html; then
          echo "❌ Test failed! Sending SNS alert..."
          aws sns publish --topic-arn arn:aws:sns:ap-southeast-1:110581573910:api-alert \
            --message "Tiki API test failed. Check report in S3."
        else
          echo "✅ All tests passed!"
        fi

artifacts:
  files:
    - report.html



